### ISSUE TITLE
Weird generation issue (possibly mod conflict)

### ISSUE THREAD

**Issue by brisingraerowing** [SmartStreamLabs/Create-Sky-Village#1]
Not sure where the issue lies here. I have 489 mods, so checking might take a bit.

![2024-09-19_16 06 52](https://github.com/user-attachments/assets/e443b1da-11ac-42aa-a45a-40a1c186cfdc)

**Comment by SmartStreamLabs** [comment]
Heya! Yes, this is indeed a mod conflict issue and  problem with Minecraft World Generation. 

I would like to help you with a solution. only, I personally wouldn't know how to solve this. Maybe you could remove the land underneath? via world edit etc

i have personally never seen anything like it in all the years of minecraft mod coding :)

We're sorry, SmartStreamLabs: Support Mei

**Comment by brisingraerowing** [comment]
A quick test with just this mod, Create and JEI still has the issue. Might be a Forge-related issue.

EDIT: Try removing the `terrain_adaptation` key in the structure data file (or set it to `none`). The `beard_*` adaptations will generate a thin bit of land under the structure.

**Comment by SmartStreamLabs** [comment]
Oh, that's annoying. I'm going to check today to see if it loads normally for me. if not, I will adjust & update the mod.

**Comment by SmartStreamLabs** [comment]
Hello, we have released an update for the mod. hopefully the problem is solved.

Please let us know!
![Minecraft Forge_ 1 20 1 21-9-2024 10_52_30](https://github.com/user-attachments/assets/42ffa3e2-a151-49e2-af7d-9ed762444eb2)

Link to the mod: https://www.curseforge.com/minecraft/mc-mods/create-sky-village/files/all?page=1&pageSize=20

**Comment by SmartStreamLabs** [comment]
###
